### PR TITLE
add latest and LTS node versions

### PR DESCRIPTION
**Pull request by mastertinner**
We should test all newer major node versions. "node" tests the latest one (which is currently 6).

### CODE REVIEW

**Comment by mastertinner** [comment]
I think we should support Node 4 (LTS). However, in case we don't, we should specify the `engines` property in `package.json` to `{ "engines" : { "node" : ">=5" } }`.

**Comment by mightea** [comment]
Under Node 4 there seems to be an issue with Babel, maybe we need `babel-preset-es2015-node4`? @mastertinner have you used this before?

**Comment by mastertinner** [comment]
Unfortunately I have never used it before either... But it seems like a good workaround until the latest LTS is >4. I wonder if it's really worth the effort though.

**Comment by mightea** [comment]
The fix was to include babel as a dependency... :) node seems to have gotten better with dependency resolution over the years

**Comment by mastertinner** [comment]
nice!

**Pull request merged**
